# Use root/example as user/password credentials
version: '3.8'

services:
  mongoshell:
    image: mongo
    entrypoint: mongo mongodb+srv://storecluster-vzj67.mongodb.net/Store --username ${MONGO_USERNAME}
      